### PR TITLE
fix code

### PR DESCRIPTION
**Pull request by muslimbek77**
add

### CODE REVIEW

**Comment by muslimbek77** [comment]
add

**Review by asilbek-ismoilov — APPROVED** [review]

**Comment by asilbek-ismoilov** [comment]
yaxshi

**Review by fotimaruziyeva — APPROVED** [review]

**Review by Theesaman — APPROVED** [review]
good

**Comment by Theesaman** [comment]
good job

**Comment by muslimbek77** [comment]
good

**Pull request merged**
